Sprint1
Iker-elorrieta/R1-2DM-6 pull request #1
Opened 2024-10-28 10:48 UTC by ederperedalo

2024-10-28 11:43 UTC, Iker-elorrieta requested changes
No guardéis el array, hay que guardar objeto a objeto.
Crear 2 workouts de nivel 0 para que se vea un poco más la funcionalidad.
Lo demás esta todo bien

2024-10-28 11:43 UTC, Iker-elorrieta commented on GYMAPP_G6/src/controlador/Controlador.java
> +
Esto no se puede hacer con ID

2024-10-28 11:46 UTC, Iker-elorrieta commented
La forma de ejecutar los backups no es la correcta

2024-10-30 08:55 UTC, leiretopo reviewed
Cambios realizado

2024-10-30 09:02 UTC, Iker-elorrieta requested changes
![image](https://github.com/user-attachments/assets/40be6e58-698e-4c02-9e42-9dc004114250)
Da error, no se puede probar

2024-10-30 09:17 UTC, Iker-elorrieta requested changes
![image](https://github.com/user-attachments/assets/7674c39f-da7e-489a-8eab-1288db3b11c3)
Sigue dando el mismo problema. Por favor, probarlo antes en otros equipos para ver si funciona correctamente. No se porque lo agregáis al classpath del proyecto.

2024-10-30 09:38 UTC, Iker-elorrieta requested changes
Existen warnings
Da error al cargar los ejercicios del workout
![image](https://github.com/user-attachments/assets/342ebdbe-acf8-4b05-b756-1b3283fdbe0e)

2024-10-30 09:43 UTC, merged

2024-10-30 09:43 UTC, Iker-elorrieta commented
Los warnings!